/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Ajout (void);
GtkWidget* create_modif (void);
GtkWidget* create_listesServices (void);
GtkWidget* create_Affectation (void);
