/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Ajout;
  GtkWidget *modif;
  GtkWidget *listesServices;
  GtkWidget *Affectation;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Ajout = create_Ajout ();
  gtk_widget_show (Ajout);
  modif = create_modif ();
  gtk_widget_show (modif);
  listesServices = create_listesServices ();
  gtk_widget_show (listesServices);
  Affectation = create_Affectation ();
  gtk_widget_show (Affectation);

  gtk_main ();
  return 0;
}

